[book]
authors = ["jaywor1", "Michal Vojáček"]
language = "cs"
multilingual = false
src = "src"
title = "APS Skripta"

#[output.markdown]

[output.html]
mathjax-support = true
default-theme = "rust"
preferred-dark-theme = "ayu"
git-repository-url = "https://github.com/mvojacek/aps-skripta"
git-branch = "main"
additional-css = [
    "./theme/mdbook-admonish.css",
    "./theme/tabs.css",
    "./theme/presentationHider.css",
    "./theme/footer.css",
    "./theme/pagetoc.css",
    "./theme/spoiler.css"
]
additional-js = [
    "./theme/tabs.js",
    "./theme/presentationHider.js",
    "./theme/pagetoc.js"
]

open-on-text = "Found a bug? [Edit this page on GitHub.]"

[preprocessor.minijinja]
preprocess_summary = true
before = ["index", "links", "cmdrun"]
undefined_behavior = "strict"
templates = "templates"
prelude_string = "{% include prelude %}"
global_env = true

[preprocessor.minijinja.variables]
my_var = "my_var_value"
prelude = "prelude.md"

[preprocessor.cmdrun]
after = ["minijinja"]
before = ["index", "links"]

[preprocessor.katex]
after = ["cmdrun"]
macros = "src/macros.katex"

[preprocessor.image-size]
command = "mdbook-image-size"
after = ["cmdrun"]

[preprocessor.admonish]
command = "mdbook-admonish"
assets_version = "3.0.2" # do not edit: managed by `mdbook-admonish install`
after = ["cmdrun"]
before = ["index", "links"]

[preprocessor.quiz]
after = ["cmdrun"]
renderer = ["html"]

[preprocessor.open-on-gh]
command = "mdbook-open-on-gh"
after = ["cmdrun"]
renderer = ["html"]
[preprocessor.last-changed]
command = "mdbook-last-changed"
after = ["cmdrun"]
renderer = ["html"]

[preprocessor.toc]
command = "mdbook-toc"
renderer = ["html"]
max-level = 6
after = ["cmdrun"]

[preprocessor.kroki-preprocessor]
endpoint = "http://localhost:8000"
after = ["cmdrun"]

[preprocessor.emojicodes]
after = ["cmdrun"]

[preprocessor.embedify]
after = ["cmdrun"]

[preprocessor.footnote]
after = ["cmdrun"]

# [preprocessor.external-links] # breaks tables
# renderer = ["html"]

[preprocessor.checklist]
after = ["cmdrun"]
title = "TODOs"

[preprocessor.pagetoc]
after = ["cmdrun"]

# [output.pdf]

#[output.pandoc]
#hosted-html = "https://skripta.vojacek.org" # URL of a HTML version of the book
#
#[output.pandoc.code]
## Display hidden lines in code blocks (e.g., lines in Rust blocks prefixed by '#').
## See https://rust-lang.github.io/mdBook/format/mdbook.html?highlight=hidden#hiding-code-lines
#show-hidden-lines = false
#
#[output.pandoc.profile.pdf] # options to pass to Pandoc (see https://pandoc.org/MANUAL.html#defaults-files)
#output-file = "output.pdf" # output file (within the profile's build directory)
#to = "latex" # output format
#
## PDF-specific settings
#pdf-engine = "pdflatex" # engine to use to produce PDF output
#
## `mdbook-pandoc` overrides Pandoc's defaults for the following options to better support mdBooks
#from = "gfm+tex_math_dollars+pipe_tables"
#file-scope = true # parse each file individually before combining
#number-sections = true # number sections headings
#standalone = true # produce output with an appropriate header and footer
#table-of-contents = true # include an automatically generated table of contents
#
## Arbitrary other Pandoc options can be specified as they would be in a Pandoc defaults file
## (see https://pandoc.org/MANUAL.html#defaults-files) but written in TOML instead of YAML...
#
## For example, to pass variables (https://pandoc.org/MANUAL.html#variables):
#[output.pandoc.profile.pdf.variables]
## Set the pandoc variable named 'variable-name' to 'value'
##variable-name = "value"