services:
  mdbook:
    image: ghcr.io/mvojacek/mdbook:v4
    volumes:
      - .:/work
    working_dir: /work
    entrypoint: mdbook
    command: serve
    network_mode: host
    user: ${UID:-1000}:${GID:-1000}
    depends_on:
      - kroki-cache
      - kroki
  kroki-cache:
    image: ghcr.io/mvojacek/docker-caching-proxy:v1
    network_mode: host
    volumes:
      - ./.kroki-cache:/cache
    environment:
      - LISTEN=127.0.0.1:8000
      - UPSTREAM=http://127.0.0.1:8001
      - MAX_SIZE=200m
      - MAX_INACTIVE=1y
      - PROXY_READ_TIMEOUT=3m
  kroki:
    image: yuzutech/kroki:latest
    network_mode: host
    environment:
      - KROKI_LISTEN=127.0.0.1:8001
      - KROKI_SAFE_MODE=unsafe
      - KROKI_COMMAND_TIMEOUT=2m
      - KROKI_CONVERT_TIMEOUT=2m
      - KROKI_MAX_URI_LENGTH=16000

