FROM ubuntu:24.04

RUN apt-get update && apt-get install -y pandoc texlive-xetex texlive-latex-recommended
RUN apt-get update && apt-get install -y libssl3 git

ADD --chmod=755 ./cargo/bin/mdbook* /usr/local/bin/

ENTRYPOINT ["/usr/local/bin/mdbook"]
